language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
  - ~/.npm
  - ~/.cache
  override:
    - npm ci
    - npm run cy:verify
script:
  - npm install
  - npm test
  - npm run build
  - npm run cy:run -- --record