# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

steps:
 - task: NodeTool@0
   inputs:
    versionSpec: '10.x'
    displayName: 'Install Node.js'
 
 - script: npm ci
   displayName: 'Install NPM dependencies'
   
 - task: Cache@2
   inputs:
    key: 'npm | "$(Agent.OS)" | package-lock.json'
    restoreKeys: |
       npm | "$(Agent.OS)"
       npm
    path: $(npm_config_cache)
   displayName: Cache npm

 - script: npm install
   displayName: 'npm install'
   
 - script: npm run build
   displayName: 'npm build'

 - script: CI=true npm test
   displayName: 'run unit tests'

 - script: npm run start:ci && sleep 5 && npm run cy:run -- 
   displayName: 'Running Cypress tests'
