# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: CacheBeta@1
  inputs:
    key: npm | $(Agent.OS) | package-lock.json
    path: ~/.npm
    restoreKeys: npm | $(Agent.OS) | package-lock.json
  displayName: Cache NPM packages
- task: CacheBeta@1
  inputs:
    key: cypress | $(Agent.OS) | package-lock.json
    path: ~/.cache/Cypress
    restoreKeys: cypress | $(Agent.OS) | package-lock.json
  displayName: Cache Cypress binary  

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- script: CI=true npm test
  displayName: 'run unit tests'
