export const Active_Note_Change = 'active-note-change'
export const Theme_Change = 'theme-change'
export const Text_Change = 'text-change'

export const Show_About_Dialog = 'show-about-dialog'
export const Show_Manual_Dialog = 'show-manual-dialog'
export const Show_Replace_Dialog = 'show-replace-dialog'

export const Clear_Text = 'clear-text'
export const Welcome_Text = 'welcome-text'
export const Markdown_Text = 'markdown-text'
export const Todo_Template_Text = 'todo-template-text'
export const PMI_Template_Text = 'pmi-template-text'
export const Smart_Template_Text = 'smart-template-text'
export const Week_Template_Text = 'week-template-text'
export const HTML_Template_Text = 'html-template-text'